services:

  activemq:
    build: 
      context: .
      dockerfile: activemq.Dockerfile
    ports:
      - "8161:8161"

  producer:
    build: producer.Dockerfile

  adder:
    build: consumer.Dockerfile
    environment:
      MODE: ADDITION

  multer:
    build: subscriber.Dockerfile
    environment:
      MODE: MULTIPLICATION

